[package]

name = "autofill"
version = "1.0.0"
authors = [ "Antoine Lestrade <antoine.lestrade@gmail.com>" ]

[[bin]]

name = "autofill"

[dependencies]
getopts = "0.2.13"
rand    = "0.3.10"